# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WPvjLNcIuP_esGJ1GRH_jScF4BRfntxt
"""

# prompt: import streamlit

!pip install streamlit
import streamlit as st

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# def print_helloworld():
#   st.title("helloworld")
# 
# def main():
#   # Call the print_helloworld function
#   print_helloworld()
# 
# if __name__ == "__main__":
#   main()

! wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501